// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using Where2Pay.Data;

namespace Where2Pay.Migrations
{
    [DbContext(typeof(BillerDbContext))]
    partial class BillerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Where2Pay.Models.Agent", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<string>("Name");

                    b.Property<string>("Phone");

                    b.Property<string>("State");

                    b.Property<string>("Street1");

                    b.Property<string>("Street2");

                    b.Property<string>("Zip");

                    b.HasKey("ID");

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("Where2Pay.Models.AgentsBillers", b =>
                {
                    b.Property<int>("AgentID");

                    b.Property<int>("BillerID");

                    b.HasKey("AgentID", "BillerID");

                    b.HasIndex("BillerID");

                    b.ToTable("AgentsBillers");
                });

            modelBuilder.Entity("Where2Pay.Models.Biller", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AgentID");

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.Property<string>("Phone");

                    b.Property<string>("Web");

                    b.HasKey("ID");

                    b.HasIndex("AgentID");

                    b.ToTable("Billers");
                });

            modelBuilder.Entity("Where2Pay.Models.AgentsBillers", b =>
                {
                    b.HasOne("Where2Pay.Models.Agent", "Agent")
                        .WithMany("AgentsBillers")
                        .HasForeignKey("AgentID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Where2Pay.Models.Biller", "Biller")
                        .WithMany("AgentsBillers")
                        .HasForeignKey("BillerID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Where2Pay.Models.Biller", b =>
                {
                    b.HasOne("Where2Pay.Models.Agent", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
